NODE_TYPES = {
    "start": {
        "label": "开始",
        "icon": "▶",
        "color": "#00ff41",
        "inputs": [],
        "outputs": ["output"],
        "config": {},
        "description": "工作流入口节点",
    },
    "llm": {
        "label": "AI 对话",
        "icon": "🤖",
        "color": "#7c3aed",
        "inputs": ["input"],
        "outputs": ["output"],
        "config": {
            "prompt": "你是一个助手。请回答以下问题：\n{{input}}",
            "model": "qwen-plus",
            "temperature": 0.7,
        },
        "description": "调用大语言模型生成回答",
    },
    "condition": {
        "label": "条件判断",
        "icon": "🔀",
        "color": "#f59e0b",
        "inputs": ["input"],
        "outputs": ["true", "false"],
        "config": {
            "condition": "input",
        },
        "description": "按条件表达式走 true / false 分支，支持 == != > >= < <= contains and or",
    },
    "http": {
        "label": "HTTP 请求",
        "icon": "🌐",
        "color": "#3b82f6",
        "inputs": ["input"],
        "outputs": ["output"],
        "config": {
            "url": "https://api.example.com/data",
            "method": "GET",
            "headers": {},
            "body": "",
            "fail_on_error": True,
        },
        "description": "发送 GET/POST/PUT/PATCH/DELETE 请求获取数据",
    },
    "text": {
        "label": "文本处理",
        "icon": "📝",
        "color": "#10b981",
        "inputs": ["input"],
        "outputs": ["output"],
        "config": {
            "operation": "concat",
            "texts": ["{{input}}"],
            "separator": "\n",
            "old": "",
            "new": "",
        },
        "description": "拼接、分割、替换文本",
    },
    "loop": {
        "label": "批量循环",
        "icon": "🔁",
        "color": "#06b6d4",
        "inputs": ["input"],
        "outputs": ["output"],
        "config": {
            "source": "{{input}}",
            "separator": "\\n",
            "action": "llm",
            "prompt": "请针对以下条目生成一句摘要：\n{{item}}",
            "model": "qwen-plus",
            "temperature": 0.5,
            "max_items": 20,
            "join": "\\n\\n",
        },
        "description": "把上游列表逐项处理（调用大模型或原样收集），并发执行后聚合结果",
    },
    "end": {
        "label": "结束",
        "icon": "⏹",
        "color": "#ef4444",
        "inputs": ["input"],
        "outputs": [],
        "config": {},
        "description": "工作流结束节点",
    },
}
